version: '3'

networks:
  docker_network:
  app-one_docker_network_shared:
    external: true

services:
  webserver:
    image: nginx:stable-alpine
    container_name: app_two_webserver
    ports:
      - '92:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - docker_network
      - app-one_docker_network_shared

  mysql:
    image: mysql:5.7.29
    container_name: app_two_mysql
    restart: unless-stopped
    tty: true
    ports:
      - '9902:3306'
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - docker_network

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: app_two_php
    volumes:
      - ./src:/var/www/html
    ports:
      - '9002:9000'
    networks:
      - docker_network
      - app-one_docker_network_shared

  composer:
    image: composer:latest
    container_name: app_two_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - docker_network

  npm:
    image: node:13.7
    container_name: app_two_npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: app_two_artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - docker_network